#ifndef OBJ_LOCALIZATION_H
#define OBJ_LOCALIZATION_H

#include "Game.h"

typedef enum {
    STR_TESTSTR,
    STR_FEATUREUNIMPLIMENTED,
    STR_RESTARTWARNING,
    STR_QUITWARNINGLOSEPROGRESS,
#if GAME_VERSION != VER_100
    STR_QUITWARNING,
#endif
    STR_DELETEPOPUP,
    STR_CONNECTING,
    STR_LOADINGFROMSERVER,
    STR_COMMERROR,
    STR_NOWIFI,
    STR_EXITCOMP,
    STR_COMPTOTAL,
    STR_TAUNLOCKED,
    STR_COMPUNLOCKED,
    STR_PEELOUTUNLOCKED,
    STR_INSTASHIELDUNLOCKED,
    STR_ANDKNUXUNLOCKED,
    STR_DEBUGMODEUNLOCKED,
    STR_BLUESPHERESUNLOCKED,
    STR_MBMUNLOCKED,
    STR_DAGARDENUNLOCKED,
    STR_CONNECTXBOX,
    STR_LOADXBOX,
    STR_CONNECTPSN,
    STR_LOADPSN,
    STR_CONNECTSTEAM,
    STR_LOADSTEAM,
    STR_CONNECTNINTENDO,
    STR_LOADNINTENDO,
    STR_PLACEHOLDERLOGIN,
    STR_SAVELOADFAIL,
    STR_CORRUPTSAVE,
    STR_NOSAVESPACE,
    STR_NOXBOXPROFILE,
    STR_RECONNECTCONTROLLER,
    STR_RECONNECTWIRELESSCONTROLLER,
    STR_SIGNOUTDETECTED,
    STR_AUTOSAVENOTIF,
#if GAME_VERSION != VER_100
    STR_KEYALREADYBOUND,
    STR_KEYALREADYBOUNDP1,
    STR_KEYALREADYBOUNDP2,
    STR_APPLYCHANGEDSETTINGS,
    STR_VIDEOCHANGESAPPLIED,
    STR_STEAMOVERLAYUNAVAILABLE,
#endif
#if MANIA_USE_PLUS
    STR_SAVEREPLAY,
    STR_NOREPLAYSPACE,
    STR_DELETEREPLAY,
    STR_ERRORLOADINGREPLAY,
    STR_CANNOTLOADREPLAY,
    STR_LOADING,
    STR_NOREPLAYS,
    STR_AREYOUSURE,
    STR_AREYOUSURESAVE,
    STR_UPTO4PLAYERS,
    STR_RESETTIMESWARNING,
    STR_MIGHTYRAYPLUS,
    STR_ENCOREREQUIRED,
    STR_RETRURNINGTOTITLE,
    STR_DEFAULT,
    STR_SELECTATRACK,
    STR_SELECTDATATOERASE,
    STR_RPC_PLAYING,
    STR_RPC_MENU,
    STR_RPC_MANIA,
    STR_RPC_ENCORE,
    STR_RPC_TA,
    STR_RPC_COMP,
    STR_RPC_TITLE,
#if MANIA_USE_EGS
    STR_CONNECTEGS,
    STR_LOADEGS,
    STR_OPENBROWSER,
    STR_ACHIEVEMENT,
    STR_NOWAYNOWAY,
    STR_FULLMEDALJACKET,
    STR_MAGNIFICENTSEVEN,
    STR_SEEYOUNEXTGAME,
    STR_SUPERSTAR,
    STR_THATSATWOFER,
    STR_NOWITCANTHURTYOU,
    STR_TRIPLETROUBLE,
    STR_FAMOUSHEDGEHOG,
    STR_WINDOWSHOPPING,
    STR_CRATEEXPECTATIONS,
    STR_KINGOFSPEED,
    STR_BOATENTHUSIAST,
    STR_THEPASSWORDIS,
    STR_SECRETSUB,
    STR_WITHOUTATRACE,
    STR_COLLECTEMALL,
    STR_PROFESSIONALHEDGEHOG,
#endif
#else
#if GAME_VERSION != VER_100
    STR_DEFAULT,
#endif
    STR_SELECTATRACK,
    STR_RPC_PLAYING,
    STR_RPC_MENU,
    STR_RPC_MANIA,
    STR_RPC_TA,
    STR_RPC_COMP,
    STR_RPC_TITLE,
#endif
    STR_CONFIRM,
    STR_BACK,
    STR_ADDENDUMOPTIONS,
    STR_MAINMENU,
    STR_MANIAMODE,
    STR_ENCOREMODE,
    STR_TIMEATTACK,
    STR_COMPETITION,
    STR_OPTIONS,
    STR_EXTRAS,
    STR_EXIT,
    STR_DELETE,
    STR_SIDEKICK,
    STR_SONIC,
    STR_TAILS,
    STR_KNUX,
    STR_MIGHTY,
    STR_RAY,
    STR_AMY,
    STR_REPLAYS,
    STR_GO,
    STR_RESET,
    STR_LEADERBOARDS,
    STR_ACT,
    STR_TOPRANK,
    STR_SORT,
    STR_BYDATE,
    STR_BYZONE,
    STR_ITEMS,
    STR_FIXED,
    STR_TELEPORTERS,
    STR_RANDOM,
    STR_MATCHLENGTH,
    STR_SCREENLAYOUT,
    STR_SUPERRUN,
    STR_OFF,
    STR_SUPER,
    STR_MIRACLE,
    STR_HYPER,
    STR_OK,
    STR_VIDEO,
    STR_SOUND,
    STR_CONTROLS,
    STR_LANGUAGE,
    STR_DATA,
    STR_APPLY,
    STR_SCREENFILTER,
    STR_NONE,
    STR_CLEAN,
    STR_CRTSHARP,
    STR_CRTSOFT,
    STR_WINDOWSIZE,
    STR_1X,
    STR_2X,
    STR_3X,
    STR_4X,
    STR_WINDOWBORDER,
    STR_ON,
    STR_FULLSCREEN,
    STR_VSYNC,
    STR_TRIPLEBUFFER,
    STR_DEFAULT2,
    STR_KEYBOARD1,
    STR_KEYBOARD2,
    STR_BUTTONCONFIG,
    STR_ENGLISH,
    STR_FRENCH,
    STR_ITALIAN,
    STR_GERMAN,
    STR_SPANISH,
    STR_JAPANESE,
    STR_KOREAN,
    STR_SIMPLECHINESE,
    STR_TRADCHINESE,
    STR_EUSKARA,
    STR_SAVEDGAMES,
    STR_MEDALLIONS,
    STR_ALLGAMEDATA,
    STR_TIMEATTACKDATA,
    STR_BLUESPHERES,
    STR_ORIGINAL,
    STR_MANIA,
    STR_MEANBEAN,
    STR_1PVSCPU,
    STR_1PVS2P,
    STR_DAGARDEN,
    STR_STAFFCREDITS,
    STR_GAMEPLAY,
    STR_STYLE,
    STR_MUSIC,
    STR_MULTIPLAYER,
    STR_GAMEPLAYOPTIONS,
    STR_TIMELIMIT,
    STR_DEBUGMODE,
    STR_SONICMOVESET,
    STR_TAILSMOVESET,
    STR_KNUXMOVESET,
    STR_MIGHTYMOVESET,
    STR_RAYMOVESET,
    STR_AMYMOVESET,
    STR_PEELOUT,
    STR_SPINDASH,
    STR_LIFESYSTEM,
    STR_SECONDGEMS,
    STR_SHIELDTRANSFER,
    STR_ITEMBOXSHIELDS,
    STR_ADDENDUM,
    STR_S3K,
    STR_CD,
    STR_ONLYSONIC,
    STR_ALLEXCEPTAMY,
    STR_ALL,
    STR_NORMAL,
    STR_UNCAPPED,
    STR_INFINITE,
    STR_SUPEREMERALDS,
    STR_TIMESTONES,
    STR_ONLYBLUE,
    STR_ONLYBUBBLE,
    STR_ONLYFIRE,
    STR_ONLYLIGHTNING,
    STR_CYCLEELEMENTAL,
    STR_CYCLEALL,
    STR_STYLEOPTIONS,
    STR_SPRITESTYLE,
    STR_CEP,
    STR_EMERALDPALETTE,
    STR_S1,
    STR_S2,
    STR_MUSICOPTIONS,
    STR_SUPERMUSIC,
    STR_VAPEMODE,
    STR_COOPSTYLE,
    STR_COOPERATIVE,
    STR_INDIVIDUAL,
    STR_ENCORE,
    STR_NEXT,
    STR_STRING_COUNT,
} GameStrings;

// Object Class
struct ObjectLocalization {
    RSDK_OBJECT
    String text;
    String strings[62];
    bool32 loaded;
    uint8 language;
};

typedef struct {
    String strings[64];
} Localization2;

typedef struct {
    String strings[64];
} Localization3;

typedef struct {
    String strings[64];
} Localization4;

// Entity Class
struct EntityLocalization {
    RSDK_ENTITY
};

// Object Struct
extern ObjectLocalization *Localization;

// Standard Entity Events
void Localization_Update(void);
void Localization_LateUpdate(void);
void Localization_StaticUpdate(void);
void Localization_Draw(void);
void Localization_Create(void *data);
void Localization_StageLoad(void);
#if GAME_INCLUDE_EDITOR
void Localization_EditorDraw(void);
void Localization_EditorLoad(void);
#endif
void Localization_Serialize(void);

// Extra Entity Functions
void Localization_LoadStrings(void);
void Localization_GetString(String *string, uint8 id);
void Localization_GetZoneName(String *string, uint8 zone);
void Localization_GetZoneInitials(String *string, uint8 zone);

#endif //! OBJ_LOCALIZATION_H
